### ISSUE TITLE
Couple suggestions

### ISSUE THREAD

**Issue by jaredhanson11** [jhanreg11/personal-website#4]
- [ ] I would merge your new-site branch to master to make it more clear if someone checks out source code which branch is actually deployed right now to match jacob-hanson.com
- [x] make the link to your resume more obvious, maybe. Ultimately I think it's visually appealing with that icon so if you can incorporate a different spot to also have a link to your resume or at a minimum have a tooltip so that when you hover over your resume icon it says resume in the tooltip. Lookup tooltip if you don't know what that is
- [x] when addressing issues, link the commit or PR that fixes that issue when you close the issue. It allows for better tracking when you look through your completed issues, if you ever have an issue or need to answer someones question etc.
- [x] the title of the resume page, so like the text that is actually on the tab itself in the browser, reads "Microsoft Word - Jacob Hanson". Idk if you have control over that, it's probably something to do with the metadata or how different browsers read PDF's. try to change that toe like Jacob Hanson - Resume, or probably even better just Jacob Hanson to match the rest of your site. might not be possible but look into it maybe

(it's also generally better practice to split ^^ items into different issues because then you can individually track them and close them, you don't have to tag three different commits to fix three different issues, i was just lazy and didn't want to open three different issues)  

oh final thing, use labels on these issues i open. So read my issue, determine what type of issue it is (bug, feature request, etc.) and use the labels section on the right to tag different issues. Allows you to filter for different things. For example, you want as little amount of bugs possible so you'd take on solving an issue tagged "bug" before "feature request"

this issue I think should be classified as enhancement IMO

**Comment by jhanreg11** [comment]
79dc3dfe3e3545c1280542533de1d9784a97b42c
